import type { Metadata } from "next";
import { Inter,Open_Sans } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });
const sance=Open_Sans({subsets : ['cyrillic']})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={sance.className}>
        <Navbar/>{children}<Footer/></body>
    </html>
  );
}
